       SUBROUTINE AFILL(X,I,J,K,A)
C SUBPROGRAM:    AFILL
C   PRGMMR: LILLY            ORG: NP12        DATE: 2007-07-22
C
C ABSTRACT: FILL ARRAY WITH VALUE = A
C
C PROGRAM HISTORY LOG:
C 2007-07-22 STEVEN G. LILLY -- UPDATING SOURCE CODES
C
C USAGE:    CALL AFILL(X,I,J,K,A)
C   INPUT ARGUMENT LIST:
C
C   OUTPUT ARGUMENT LIST:
C
C   SUBPROGRAM CALLED:
C     LIBRARY:    (NONE)
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN-90
C   MACHINE:  IBM RS6000
C
C$$$

       DIMENSION X(I,J,K)
       DO KK = 1,K
       DO JJ = 1,J
         DO II = 1,I
           X(II,JJ,KK) = A
         END DO
       END DO
       END DO
       RETURN
       END
