       SUBROUTINE DATECNV10(DATE1,IY,IM,ID,IH)
C SUBPROGRAM:    DATECNV10
C   PRGMMR: LILLY            ORG: NP12        DATE: 2007-07-22
C
C ABSTRACT: THIS SUBROUTINE TAKES A 10 DIGIT INTEGER DATA WORD
C YYYYMMDDHH FORMAT AND BREAKS IT UP INTO A 4 INTEGER PARTS.
C
C PROGRAM HISTORY LOG:
C 2007-07-22 STEVEN G. LILLY -- UPDATING SOURCE CODES
C
C USAGE:    CALL DATECNV10(DATE1,IY,IM,ID,IH)
C   INPUT ARGUMENT LIST:
C
C   OUTPUT ARGUMENT LIST:
C
C   SUBPROGRAM CALLED:
C     LIBRARY:    (NONE)
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN-90
C   MACHINE:  IBM RS6000
C
C$$$

       INTEGER DATE1
       CHARACTER(10)  CDATE
       CHARACTER(4)   CYEAR
       CHARACTER(2)   CMONTH, CDAY, CHOUR
 800   FORMAT (I4)
 810   FORMAT (I2)
 900   FORMAT (I10)
       WRITE (CDATE,900) DATE1
       CYEAR  =  CDATE(1:4)
       CMONTH =  CDATE(5:6)
       CDAY   =  CDATE(7:8)
       CHOUR  =  CDATE(9:10)
       READ (CYEAR,800) IY
       READ (CMONTH,810) IM
       READ (CDAY,810) ID
       READ (CHOUR,810) IH
       RETURN
       END
