       SUBROUTINE IFILL(IX,I,J,K,IA)
C SUBPROGRAM:    IFILL
C   PRGMMR: LILLY            ORG: NP12        DATE: 2007-07-22
C
C ABSTRACT: THIS SUBROUTINE FILLS ARRAY WITH VALUE = IA
C
C PROGRAM HISTORY LOG:
C 2007-07-22 STEVEN G. LILLY -- UPDATING SOURCE CODES
C
C USAGE:    CALL IFILL(IX,I,J,K,IA)
C   INPUT ARGUMENT LIST:
C
C   OUTPUT ARGUMENT LIST:
C
C   SUBPROGRAM CALLED:
C     LIBRARY:    (NONE)
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN-90
C   MACHINE:  IBM RS6000
C
C$$$
C
C***     FILL ARRAY WITH VALUE = IA
 
       DIMENSION IX(I,J,K)
       DO KK = 1,K
        DO JJ = 1,J
          DO II = 1,I
           IX(II,JJ,KK) = IA
          END DO
        END DO
       END DO
       RETURN
       END
