     
      SUBROUTINE GETDDN(RUNN,MIDLET,MIDINX,FHR,DDNAME)

C$$$  SUBROUTINE DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBROUTINE:    GETDDN      GET DDNAME FOR VERIFYING FORECASTS.  
C   PRGMMR:   VLCEK             ORG: W/NP12    DATE: 1999-06-07 
C
C ABSTRACT:  GET DDNAME FOR VERIFYING FORECASTS AND THUS ARCHIVE 
C            STATISTICS CAN BE IDENTIFIED BY CONTAINING SUCH A 
C            UNIQUE NAME IMPLICITLY INCLUDING MESSAGES ON FORECAST
C            MODEL, VALID TIMES AND WHERE THE VERIFYING AREA LOCATES
C            (N. HEM., S. HEM., TROPICS).
C
C PROGRAM HISTORY LOG:
C   1996-06-25  Y. ZHANG  
C   1998-07-28  C. VLCEK  COMPILE IN FORTRAN 90.
C   1999-06-07  C. VLCEK  COMPILE IN FORTRAN 90.
C   
C USAGE:  CALL  GETDDN(RUNN,MIDLET,MIDINX,FHR,DDNAME)
C   INPUT ARGUMENT LIST:
C
C     RUNN------C*4 ; INPUT RUN TYPE NAME.  
C     MIDLET----C*1 ; A INPUT CHARACTER COULD BE USED FOR 
C               CONSTRUCTING DDNAME DEPEND ON VALUE OF MIDINX.
C     MIDINX----INTEGER MARKING ON IF 4TH BYTE (LETTER) OF RUNN
C               WILL BE USED FOR CONSTRUCTING DDNAME:
C        = 0 :  DENOTES THAT IF 4TH BYTE (LETTER) OF RUNN DOES 
C               NOT EQUAL TO A SPACE (' '), IT WILL BE USED FOR
C               CONSTRUCTING DDNAME; OTHERWISE, INPUT MIDLET WILL 
C               REPLACE IT TO BE USED FOR CONSTRUCTING DDNAME.
C        = 1 :  DENOTES THAT ONLY INPUT MIDLET WILL BE USED FOR
C               CONSTRUCTING DDNAME. 
C     FHR-------C*4 ; FORECAST VALID TIME HEADED BY A LETTER 'F',
C               OR EXPRESSED AS 'ANAL'.
C
C   OUTPUT ARGUMENT LIST:  
C     
C     DDNAME----C*8 ; OUTPUT REQUIRED DDNAME.
C 
C   INPUT FILES: NONE
C 
C   OUTPUT FILES: NONE
C
C ATTRIBUTES: 
C   LANGUAGE: FORTRAN 90  
C   MACHINE:  IBM RS6000
C
C$$$ 

      INTEGER      MIDINX
      CHARACTER(8) DDNAME, TMPTMP
      CHARACTER(4) RUNN  , FHR   , T41    , T42
      CHARACTER(1) MIDLET, TMP(8), CRUN(4)

      EQUIVALENCE (TMP(1),T41), (TMP(5),T42)
      EQUIVALENCE (TMPTMP,TMP(1))

      T41    = RUNN
      T42    = FHR
      IF(MIDINX.EQ.0) THEN
         IF(TMP(4).EQ.' ') TMP(4) = MIDLET
      ELSE IF(MIDINX.EQ.1) THEN
         TMP(4) = MIDLET
      END IF
      DDNAME = TMPTMP

      RETURN
      END
